//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.1.3-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.10.28 at 03:39:31 PM CET
//

package fr.ign.cogit.appli.xdogs.theseMickael.regleUrba.reglesUrbanismes.regles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MinMax complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MinMax">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="VMax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MinMax", propOrder = { "vMin", "vMax" })
public class MinMax {

  public MinMax() {
  }

  public MinMax(double vMin, double vMax) {
    this.vMin = vMin;
    this.vMax = vMax;
  }

  @XmlElement(name = "VMin")
  protected double vMin;
  @XmlElement(name = "VMax")
  protected double vMax;

  /**
   * Gets the value of the vMin property.
   * 
   */
  public double getVMin() {
    return this.vMin;
  }

  /**
   * Sets the value of the vMin property.
   * 
   */
  public void setVMin(double value) {
    this.vMin = value;
  }

  /**
   * Gets the value of the vMax property.
   * 
   */
  public double getVMax() {
    return this.vMax;
  }

  /**
   * Sets the value of the vMax property.
   * 
   */
  public void setVMax(double value) {
    this.vMax = value;
  }

  @Override
  public String toString() {
    return "Valeur minimale : " + this.vMin + " m-Valeur maximale : "
        + this.vMax;
  }

}
