//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.1.3-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.10.26 at 12:24:15 PM CET
//

package fr.ign.cogit.gru3d.regleUrba.reglesUrbanismes.regles;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DistanceEuclidienne complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DistanceEuclidienne">
 *   &lt;complexContent>
 *     &lt;extension base="{}Distance">
 *       &lt;sequence>
 *         &lt;element name="dMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistanceEuclidienne", propOrder = { "dMin" })
public class DistanceEuclidienne extends Distance {

  protected double dMin;

  /**
   * Gets the value of the dMin property.
   * 
   */
  public double getDMin() {
    return this.dMin;
  }

  /**
   * Sets the value of the dMin property.
   * 
   */
  public void setDMin(double value) {
    this.dMin = value;
  }

  public DistanceEuclidienne() {

  }

  public DistanceEuclidienne(double dmin) {
    this.dMin = dmin;

  }

  @Override
  public String toString() {

    return this.dMin + "m ";
  }

}
