//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.1.3-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.10.26 at 12:24:15 PM CET
//

package fr.ign.cogit.gru3d.regleUrba.reglesUrbanismes.regles;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the regles package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of
   * schema derived classes for package: regles
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link LimitationCOS }
   * 
   */
  public LimitationCOS createLimitationCOS() {
    return new LimitationCOS();
  }

  public PLU createPLU() {
    return new PLU();
  }

  /**
   * Create an instance of {@link ReculRoute }
   * 
   */
  public ReculRoute createReculRoute() {
    return new ReculRoute();
  }

  /**
   * Create an instance of {@link ContrainteHauteur }
   * 
   */
  public ContrainteHauteur createContrainteHauteur() {
    return new ContrainteHauteur();
  }

  /**
   * Create an instance of {@link ZonePLU }
   * 
   */
  public ZonePLU createZonePLU() {
    return new ZonePLU();
  }

  /**
   * Create an instance of {@link Regle }
   * 
   */
  public Regle createRegle() {
    return new Regle();
  }

  /**
   * Create an instance of {@link ReculBordure }
   * 
   */
  public ReculBordure createReculBordure() {
    return new ReculBordure();
  }

  /**
   * Create an instance of {@link ConsequenceTexture }
   * 
   */
  public ConsequenceTexture createConsequenceTexture() {
    return new ConsequenceTexture();
  }

  /**
   * Create an instance of {@link Consequence }
   * 
   */
  /*
   * public Consequence createConsequence() { return new Consequence(); }
   */

  /**
   * Create an instance of {@link ReculAutreBatiment }
   * 
   */
  public ReculAutreBatiment createReculAutreBatiment() {
    return new ReculAutreBatiment();
  }

  /**
   * Create an instance of {@link Interdiction }
   * 
   */
  public Interdiction createInterdiction() {
    return new Interdiction();
  }

  /**
   * Create an instance of {@link TypeBatiment }
   * 
   */
  public TypeBatiment createTypeBatiment() {
    return new TypeBatiment();
  }

  /**
   * Create an instance of {@link DifferenceHauteur }
   * 
   */
  public DifferenceHauteur createDifferenceHauteur() {
    return new DifferenceHauteur();
  }

  /**
   * Create an instance of {@link BandeConstructibilite }
   * 
   */
  public BandeConstructibilite createBandeConstructibilite() {
    return new BandeConstructibilite();
  }

  /**
   * Create an instance of {@link DistanceFHauteur }
   * 
   */
  public DistanceFHauteur createDistanceFHauteur() {
    return new DistanceFHauteur();
  }

  /**
   * Create an instance of {@link Recul }
   * 
   */
  /*
   * public Recul createRecul() { return new Recul(); }
   */

  /**
   * Create an instance of {@link DistanceEuclidienne }
   * 
   */
  public DistanceEuclidienne createDistanceEuclidienne() {
    return new DistanceEuclidienne();
  }

  /**
   * Create an instance of {@link RouteBordante }
   * 
   */
  public RouteBordante createRouteBordante() {
    return new RouteBordante();
  }

  /**
   * Create an instance of {@link ConsequenceHauteur }
   * 
   */
  /*
   * public ConsequenceHauteur createConsequenceHauteur() { return new
   * ConsequenceHauteur(); }
   */

  /**
   * Create an instance of {@link AngleToit }
   * 
   */
  public AngleToit createAngleToit() {
    return new AngleToit();
  }

  /**
   * Create an instance of {@link LimitationCES }
   * 
   */
  public LimitationCES createLimitationCES() {
    return new LimitationCES();
  }

  /**
   * Create an instance of {@link Distance }
   * 
   */
  public Distance createDistance() {
    return new Distance();
  }

  /**
   * Create an instance of {@link Antecedent }
   * 
   */
  /*
   * public Antecedent createAntecedent() { return new Antecedent(); }
   */

}
