//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.1.3-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.10.26 at 12:24:15 PM CET
//

package fr.ign.cogit.gru3d.regleUrba.reglesUrbanismes.regles;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ZonePLU complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ZonePLU">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="comporte" type="{}Regle" maxOccurs="unbounded"/>
 *         &lt;element name="LienDocument" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZonePLU", propOrder = { "nom", "regles", "lienDocument" })
public class ZonePLU {

  @XmlElement(required = true)
  protected String nom;
  @XmlElement(required = true)
  protected List<Regle> regles;
  @XmlElement(name = "LienDocument", required = true)
  protected String lienDocument;

  public ZonePLU() {

  }

  public ZonePLU(String nomZone, String url) {
    this.nom = nomZone;
    this.regles = new ArrayList<Regle>();
    this.lienDocument = url;
  }

  /**
   * Gets the value of the nom property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getNom() {
    return this.nom;
  }

  /**
   * Sets the value of the nom property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setNom(String value) {
    this.nom = value;
  }

  /**
   * Gets the value of the comporte property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot.
   * Therefore any modification you make to the returned list will be present
   * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
   * for the comporte property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
   * getComporte().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Regle }
   * 
   * 
   */
  public List<Regle> getRegles() {
    if (this.regles == null) {
      this.regles = new ArrayList<Regle>();
    }
    return this.regles;
  }

  /**
   * Gets the value of the lienDocument property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLienDocument() {
    return this.lienDocument;
  }

  /**
   * Sets the value of the lienDocument property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setLienDocument(String value) {
    this.lienDocument = value;
  }

}
